on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/*.yaml'
      - '.github/actions/*/action.yaml'
      - 'ergogen/footprints/*.js'
      - 'ergogen/config.yaml'
      - 'kibot/*'
      - 'freerouting/*'
      - 'package.json'
      - '*.nix'

name: Build
jobs:
  board:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Docker Cache
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs with Ergogen (definition in package.json)
        run: npm run build
      - name: Run KiBot to generate images, gerbers for the plates
        uses: ./.github/actions/kibot
        with:
          boards: left_pcb right_pcb
          config: default
      - name: Run KiBot to generate images, gerbers for the unrouted board
        uses: ./.github/actions/kibot
        with:
          boards: left_pcb right_pcb
          config: default
      - name: Export DSN file for Freerouting
        uses: ./.github/actions/export-dsn
        with:
          boards: left_pcb right_pcb
      - name: Autoroute PCB
        uses: ./.github/actions/autoroute
        with:
          boards: left_pcb right_pcb
      - name: Import SES
        uses: ./.github/actions/import-ses
        with:
          boards: left_pcb right_pcb
      - name: Run KiBot to generate images, gerbers for the autorouted board
        uses: ./.github/actions/kibot
        with:
          boards: left_pcb right_pcb
          config: boards
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: ergogen/output
      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: typematrix_split 
          path: ergogen/output
      - name: Persist output for pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ergogen/output
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: board
    
    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
